repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.2"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--output-format=full"]
        exclude: ^.*\.(ipynb)$
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: compileall
        name: Compile all python files
        entry: sh -c 'PYTHONWARNINGS=error python3 -m compileall -q .'
        language: python
        pass_filenames: false
